import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div style={{ height: "100vh", padding: "20px", backgroundColor: "#232323", color: "white" }}>
      <h1 style={{ fontSize: "48px", marginBottom: "20px" }}>Homepage</h1>
      <p style={{ fontSize: "18px", marginBottom: "30px" }}>
        This project was generated By{" "}
        <a href="https://www.dhiwise.com" style={{ color: "#87CEFA", textDecoration: "none" }}>
          Dhiwise
        </a>
        . Quickly use below links to navigate through all pages.
      </p>
      <ul style={{ listStyle: "none", padding: "0" }}>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/desktopmaindashboard" style={{ color: "#87CEFA", textDecoration: "none" }}>
            DESKTOPMAINDASHBOARD
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/tempcontrol" style={{ color: "#87CEFA", textDecoration: "none" }}>
            TempControl
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/lightlevelcontrol" style={{ color: "#87CEFA", textDecoration: "none" }}>
            LightLevelControl
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/nutrientcontrol" style={{ color: "#87CEFA", textDecoration: "none" }}>
            NutrientControl
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/main" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Main
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/intro" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Intro
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/work" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Work
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/about" style={{ color: "#87CEFA", textDecoration: "none" }}>
            About
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/signup" style={{ color: "#87CEFA", textDecoration: "none" }}>
            SignUP
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/signupone" style={{ color: "#87CEFA", textDecoration: "none" }}>
            SignUPOne
          </Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
